### ISSUE TITLE
Add entities essential missing

### ISSUE THREAD

**Issue by TiagoDanin** [TiagoDanin/htmlEntities-for-lua#4]
*Level*: Easy
Add entities essential missing

[Hacktoberfest 2017](https://hacktoberfest.digitalocean.com/) 🎉

**Comment by luizcavalcanti** [comment]
Hey Tiago. Interested in helping. Could you be more specific?

**Comment by TiagoDanin** [comment]
Works with [HTML 4 Entities](https://www.w3schools.com/charsets/ref_html_entities_4.asp). But with HTML 5 Entities no.

Example: 
Input: `&#x1f609;`
Output: `&#x1f609;`
Expected: `😉`

**Comment by TiagoDanin** [comment]
Done!
