### ISSUE TITLE
Encode quotes with their literal representation by default

### ISSUE THREAD

**Issue by d9k** [TiagoDanin/htmlEntities-for-lua#6]
`htmlEntities.encode('"') -- encode double quote`

Expected: `&quot;`
Actual Result: `"`

**Comment by TiagoDanin** [comment]
Thank you for reporting the problem :)

**Comment by TiagoDanin** [comment]
![image](https://user-images.githubusercontent.com/5731176/38390853-e9224d4a-38f8-11e8-99ac-87b2e7d91cdd.png)
Fix this in [v1.3.0](https://github.com/TiagoDanin/htmlEntities-for-lua/releases/tag/1.3.0)

**Comment by d9k** [comment]
@TiagoDanin, thanks for fast solution! :wink: :+1:
