### ISSUE TITLE
Decode querystring

### ISSUE THREAD

**Issue by lozaericml** [TiagoDanin/htmlEntities-for-lua#9]
Hi!

I guess the module was intended to work if string contains only html entities. I'm trying to decode a querystring and there's a problem. 

Example:
`htmlEntities = require('htmlEntities')
print(htmlEntities.decode('a=1&b=2&c=3&amp;d=4'))`

It shows 
`a=1&b=2&c=3&amp;d=4`
 but must show 
`a=1&b=2&c=3&d=4`

This can fix it:
`local output = string.gsub(input, '&[%w#]-;', htmlEntities_table)`
https://github.com/TiagoDanin/htmlEntities-for-lua/blob/e63b4e6c1faf9b90ba81084481f090d364693c01/src/htmlEntities.lua#L2354

PD: I know my use case does not respect the querystring standard
PD2: English isn’t my first language, so please excuse any mistakes.

**Comment by TiagoDanin** [comment]
@lozaericml Thanks, could you open a pull request with the modification?

**Comment by lozaericml** [comment]
of course! #12

**Comment by lozaericml** [comment]
Thanks!

**Comment by TiagoDanin** [comment]
Patch already available via LuaRocks or GitHub Releases ([1.3.1](https://github.com/TiagoDanin/htmlEntities-for-lua/releases/tag/1.3.1))!
